event/urls.py
from django.urls import path

from event.views import (
    index, winner_list,add_players
)

app_name = 'event'

urlpatterns = [
    path('', index, name='index'),
    path('winner/', winner_list, name='winner'),
    path('add_players/', add_players, name='add_players'),

]

match/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls', namespace='race'))
]

event/models.py
from django.db import models


class Player(models.Model):
    players = models.CharField('Player', max_length=100)

    def __str__(self):
        return self.players


class WinnerPlayer(models.Model):
    player_a = models.ForeignKey(Player, related_name='player_a', on_delete=models.CASCADE)
    player_b = models.ForeignKey(Player, related_name='player_b', on_delete=models.CASCADE)
    winner = models.ForeignKey(Player, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

event/forms.py
from django.forms import ModelForm

from . import models


class PresetListForm(ModelForm):
    class Meta:
        model = models.WinnerPlayer

event/views.py
from django.contrib import messages
from django.db.models import Count, Max
from django.shortcuts import render, redirect

from event.models import Player, WinnerPlayer


def index(request):
    player = Player.objects.all().order_by('-id')
    current_standing = WinnerPlayer.objects.values('winner__players').annotate(
        winner_count=Count('winner')).order_by('-winner_count')[:5]
    maxi = None
    if len(current_standing):
        maxi = current_standing[0]

    if request.method == 'POST':
        player_name_a = request.POST['p1']
        player_name_b = request.POST['p2']
        winner = request.POST['winner']
        WinnerPlayer.objects.create(
            player_a=Player.objects.filter(id=player_name_a).first(),
            player_b=Player.objects.filter(id=player_name_b).first(),
            winner=Player.objects.filter(id=winner).first(),
        )
        messages.success(request, 'Winner Added Successfully')
        return redirect('race:index')
    return render(request, 'event/index.html', {'player': player, 'st': current_standing, 'maxi':maxi})


def winner_list(request):
    winner = WinnerPlayer.objects.all().order_by('-id')

    return render(request, 'event/winner.html',
                  {'winner': winner}
                  )


def add_players(request):
    if request.method == 'POST':
        players = request.POST['add_player']
        Player.objects.create(
            players=players,
        )
        messages.success(request, 'Player Added Successfully!')
        return redirect('race:add_players')
    return render(request, 'event/add_player.html')

event/templates/event/add_player.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Add Players!</title>
    <link rel="stylesheet" href="{% static 'event/style.css' %}">
    <style>
        #size{
        width: 50%;
        text-align:center;
        }
        body{
        background-color: #d3d3d3;
        }


    </style>

</head>
<body>
<div class="container">
    <form method="post" action="{% url 'race:add_players' %}">
        {% csrf_token %}
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <br>
        <input type="text" id="size" name="add_player" placeholder="Enter player name">
        <br><br>
        <input type="submit" value="Add"> &nbsp;&nbsp;<a href="{% url 'race:index' %}">Back to home!!</a>


    </form>
</div>
</body>
</html>

event/templates/event/admin_panel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Admin Panel!!</title>

</head>
<body>
<div class="form-container sign-in-container">
        <form action="#">
            {% csrf_token %}
            <span>Player 1</span>
            <select>
            {% for data in player %}
                <option value={{data.players}}>{{data.players}}</option>
            {% endfor %}
            </select>
            <span>Player 2</span>
            <select>
            {% for data in player %}
                <option value={{data.players}}>{{data.players}}</option>
            {% endfor %}
            </select>
            <span>Winner</span>
            <select>
            {% for data in player %}
                <option value={{data.players}}>{{data.players}}</option>
                <option value='tie'>Tie</option>
            {% endfor %}
            </select>
            <button>
                <a style="color:white;" href="{% url 'race:winner' %}">View more
                </a>
            </button>

        </form>
    </div>
</body>
</html>

event/templates/event/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge"/>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'event/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <title>Race Event</title>
</head>
<body>

<h2> Race Event!</h2>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
<div class="container" id="container">

    <div class="form-container sign-up-container">

        <h1 style="text-align:center;">Add Winner!</h1>
        <form action="{% url 'race:index' %}" method="post">
            {% csrf_token %}
            <a href="{% url 'race:add_players' %}">Add More Player!!</a>

            <span>Player A</span>
            <select name="p1" id="p1" required>
                <option value="" selected disabled hidden>-- select one -- </option>
                {% for data in player %}
                <option value={{data.id}}>{{data.players}}</option>
                {% endfor %}
            </select>
            <span>Player B</span>

            <select name="p2" id="p2" required>
                <option value="" selected disabled hidden>-- select one -- </option>
                {% for data in player %}
                <option value={{data.id}}>{{data.players}}</option>
                {% endfor %}
            </select>
            <span>Winner</span>
            <select name="winner" id="winner" required>
                <option value="" selected disabled hidden>-- select one -- </option>
                <option id='pl1' value="">Player1 </option>
                <option id='pl2' value="">Player2 </option>
            </select>
            <button type="submit">
                Submit
            </button>

        </form>
    </div>

    <div class="form-container sign-in-container">
        <form action="#">
            <small>Final Winner is: {{maxi.winner__players}} Total win: {{maxi.winner_count}}</small>
            <h4>Top 5 Player</h4>
            <table border="1">
                <tr>
                    <th>Player Name</th>
                    <th>Match Win</th>
                </tr>
                {% for data in st %}
                <tr>
                    <td>{{data.winner__players}}</td>
                    <td>{{data.winner_count}}</td>
                </tr>
                {% endfor %}

            </table>
            <br>
            <button>
                <a style="color:white;" href="{% url 'race:winner' %}">View Races
                </a>
            </button>

        </form>
    </div>

    <div class="overlay-container">
        <div class="overlay">
            <div class="overlay-panel overlay-left">
                <h1>Welcome Back!</h1>
                <p>Click here to See the Race Results.</p>
                <button class="ghost" id="signIn">View Result</button>
            </div>
            <div class="overlay-panel overlay-right">
                <h1>Hello, Friend!</h1>
                <p>Choose Winner!!</p>
                <button class="ghost" id="signUp">Add Winner</button>
            </div>
        </div>
    </div>
</div>

</body>

<script src="{% static 'event/main.js' %}"></script>


</html>

event/templates/event/winner.html
{% load static %}
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'event/style.css' %}">

    <title> Race Event </title>

</head>
<body>

<!--showing result here-->
<main role="main" class="container">
    <h2>Total Races List <small>&nbsp;&nbsp;<a href="{% url 'race:index' %}">Click here to home!!</a></small></h2>
    <div class="media-body" align="center">
        <table border="1" style="text-align:center;">
            <tr>
                <th>S.No</th>
                <th>Player A</th>
                <th>Player B</th>
                <th>Winner</th>
            </tr>
            {% for all in winner%}
            <tr>
                <td>
                    {{forloop.counter}}
                </td>
                <td>
                    {{all.player_a}}
                </td>
                <td>
                    {{all.player_b}}
                </td>
                <td>
                    <b>{{all.winner}}</b>
                </td>
            </tr>
            {%endfor%}
        </table>
    </div>
</main>
</body>
</html>